function im_ = cropAndNormalizeIm( im, imSize, tlbr, rgbMean )
    r = tlbr( 3 ) - tlbr( 1 ) + 1; c = tlbr( 4 ) - tlbr( 2 ) + 1;
    imc = im( ...
        max( 1, tlbr( 1 ) ) : min( imSize( 1 ), tlbr( 3 ) ), ...
        max( 1, tlbr( 2 ) ) : min( imSize( 2 ), tlbr( 4 ) ), : );
    if tlbr( 1 ) >= 1 && tlbr( 2 ) >= 1 ...
            && imSize( 1 ) >= tlbr( 3 ) ...
            && imSize( 2 ) >= tlbr( 4 ), ...
            im_= bsxfun( @minus, imc, rgbMean ); return;
    end;
    im_ = zeros( r, c, numel( rgbMean ), 'single' );
    im_( ...
        max( 2 - tlbr( 1 ), 1 ) : min( imSize( 1 ) - tlbr( 3 ) + r, r ), ...
        max( 2 - tlbr( 2 ), 1 ) : min( imSize( 2 ) - tlbr( 4 ) + c, c ), : )...
        = bsxfun( @minus, imc, rgbMean );
end