function plottlbr( tlbrs, im, wait, color, cnames )
    if nargin < 4,
        color = 'c';
    end
    rects = tlbr2rect( tlbrs );
    imshow( im ); hold on; cnt = 0;
    for rect_ = rects; cnt = cnt + 1;
        rectangle( 'Position', rect_, 'EdgeColor', color, 'LineWidth', 2 );
        if nargin > 4,
            text( ...
                double( rect_( 1 ) ), ...
                double( rect_( 2 ) ), ...
                cnames{ cnt }, ...
                'color', 'k', ...
                'FontSize', 14, ...
                'BackgroundColor', color );
        end
        if wait, waitforbuttonpress; hold off; imshow( im ); hold on; end;
    end; 
    if nargin > 4 && ~wait, cnt = 0;
        for rect_ = rects; cnt = cnt + 1;
            text( ...
                double( rect_( 1 ) ), ...
                double( rect_( 2 ) ), ...
                cnames{ cnt }, ...
                'color', 'k', ...
                'FontSize', 14, ...
                'BackgroundColor', color );
        end;
    end; hold off;
end

